name: build-registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "45 */7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: runiverse/base
    env:
      GITHUB_PAT: ${{ secrets.TOKEN2 }}
      GITHUB_GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
      REPO_PAT: ${{ secrets.REPO_PAT }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
    - uses: actions/checkout@v2
    - name: Install Ruby gems
      run: |
        apt-get update
        apt-get install -y ruby-faraday ruby-json ruby-octokit
    - name: Install R dependencies and makeregistry
      run: |
        install.packages(c("remotes", "gert", "dplyr", "desc"))
        remotes::install_deps(dependencies = TRUE)
        remotes::install_local(".")
      shell: Rscript {0}
    - name: Make directories
      run: |
        mkdir repos repos/other repos/ropensci repos/ropenscilabs repos/ropensci-archive
    - name: Copy files
      run: |
        echo repos/ropenscilabs repos/ropensci repos/ropensci-archive | xargs -n 1 cp inst/automation/clone_repos.rb
        cp inst/automation/pull_other.sh repos/other
        cp inst/automation/last_commits.R inst/automation/last_commits.sh inst/automation/make_registry.R inst/automation/make_registry.sh .
    - name: Clone repos
      run: |
        cd repos/ropenscilabs
        ruby clone_repos.rb ropenscilabs
        cd ../ropensci
        ruby clone_repos.rb ropensci
        cd ../ropensci-archive
        ruby clone_repos.rb ropensci-archive
        cd ../other
        bash pull_other.sh
        cd ../../
    - name: Make last commit.csv
      run: |
        sh last_commits.sh
        head last_commits.csv
    - name: Make registry, push to roregistry
      run: |
        git config --global user.email "myrmecocystus+ropenscibot@gmail.com"
        git config --global user.name "ropenscibot"
        sh make_registry.sh
