name: build-registry

on: push

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Make directories
      run: |
        mkdir repos
        mkdir repos/other
        mkdir repos/ropensci
        mkdir repos/ropenscilabs
        cd repos/ropenscilabs
        cp inst/automation/pull_ropenscilabs2.sh .
        bash pull_ropenscilabs2.sh
        cd ../../
        ls repos/ropenscilabs
