name: build-registry

on: push

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Setup R
      uses: r-lib/actions/setup-r@master
      with:
        r-version: release
    - name: Query R dependencies
      run: |
        install.packages('remotes')
        saveRDS(remotes::dev_package_deps(dependencies = TRUE), ".github/depends.Rds", version = 2)
        writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
      shell: Rscript {0}
    - name: Cache R packages
      uses: actions/cache@v1
      with:
        path: ${{ env.R_LIBS_USER }}
        key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
        restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libgit2-dev libcurl4-openssl-dev
    - name: Install R dependencies
      run: |
        remotes::install_cran(c("gert", "dplyr"))
      shell: Rscript {0}
    - name: Make directories
      run: |
        mkdir repos
        mkdir repos/other
        mkdir repos/ropensci
        mkdir repos/ropenscilabs
    - name: Copy files
      run: |
        cp inst/automation/pull_ropenscilabs2.sh repos/ropenscilabs
        cp inst/automation/pull_ropensci2.sh repos/ropensci
        cp inst/automation/pull_other.sh repos/other
        cp inst/automation/last_commits.R .
        cp inst/automation/last_commits.sh .
    - name: Clone repos
      run: |
        cd repos/ropenscilabs
        bash pull_ropenscilabs2.sh
        cd ../ropensci
        bash pull_ropensci2.sh
        cd ../other
        bash pull_other.sh
        cd ../../
    - name: Make last commit.csv
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        sh last_commits.sh
        head last_commits.csv
