name: build-registry

on:
  workflow_dispatch:
  push:
    branches:
      - master
  schedule:
    - cron: "45 */7 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container: runiverse/base
    env:
      GITHUB_PAT: ${{ secrets.TOKEN2 }}
      GITHUB_GRAPHQL_TOKEN: ${{ secrets.GRAPHQL_TOKEN }}
      REPO_PAT: ${{ secrets.GRAPHQL_TOKEN }}
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: false
    steps:
    - uses: actions/checkout@v2
    - uses: r-lib/actions/setup-r@v2
    - uses: r-lib/actions/setup-r-dependencies@v2
      with:
        cache-version: 2
    - name: Install package
      run: |
        install.packages("remotes")
        remotes::install_local()
      shell: Rscript {0}
    - name: Build registry
      run: |
        makeregistry::build_ropensci_packages_json()
      shell: Rscript {0}
    - name: Make last commit.csv
      run: |
        sh last_commits.sh
        head last_commits.csv
    - name: Make registry, push to roregistry
      run: |
        git config --global user.email "accounts+ropenscibot@ropensci.org"
        git config --global user.name "ropenscibot"
        sh make_registry.sh
