name: build-registry

on: push

jobs:
  build:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      working-directory: 
    steps:
    - uses: actions/checkout@v2
    - name: Setup Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 2.7
    - name: Make directories
      run: |
        mkdir repos
        mkdir repos/other
        mkdir repos/ropensci
        mkdir repos/ropenscilabs
        pwd
